spring.application.name=fluxocaixa

spring.datasource.url=jdbc:mysql://localhost:3306/bd_fluxo?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true